from typing import Any, Dict
from .registry import CapabilityRegistry

class RESTAdapter:
    def __init__(self, registry: CapabilityRegistry):
        self.registry = registry

    def handle_request(self, endpoint: str, method: str, body: dict, context: dict = None) -> Dict[str, Any]:
        if context is None:
            context = {}

        # Very simple routing: assume endpoint is /api/capabilities/{capability_id}
        parts = endpoint.strip("/").split("/")
        if len(parts) != 3 or parts[0] != "api" or parts[1] != "capabilities":
            return {"status": 404, "error": "Not Found"}

        cap_id = parts[2]
        cap = self.registry.get(cap_id)

        if not cap or "api" not in cap.supported_surfaces:
            return {"status": 404, "error": "Capability not found or not supported via API"}

        if method != "POST":
            return {"status": 405, "error": "Method Not Allowed"}

        context["surface"] = "api"

        try:
            result = cap.execute(body, context)

            response = {"status": 200, "data": result}
            if cap.evidence_required:
                response["effect_receipt"] = {
                    "capability_id": cap.capability_id,
                    "version": cap.version,
                    "domain_owner": cap.domain_owner,
                    "surface": "api",
                    "effect_class": cap.effect_class,
                    "evidence": "generated by API adapter"
                }
            return response
        except ValueError as e:
            return {"status": 400, "error": str(e)}
        except Exception as e:
            return {"status": 500, "error": str(e)}
