import argparse
import sys
import json
from typing import List, Optional
from .registry import CapabilityRegistry

class CLIAdapter:
    def __init__(self, registry: CapabilityRegistry):
        self.registry = registry
        self.parser = argparse.ArgumentParser(description="A'Space Capability CLI")
        self.subparsers = self.parser.add_subparsers(dest="capability", help="Capability to execute")

        for cap in self.registry.list_capabilities():
            if "cli" in cap.supported_surfaces:
                cap_parser = self.subparsers.add_parser(cap.capability_id, help=cap.intent)

                # Add arguments based on schema
                for prop_name, prop_def in cap.input_schema.get("properties", {}).items():
                    required = prop_name in cap.input_schema.get("required", [])
                    help_text = prop_def.get("description", "")

                    if prop_def.get("type") == "boolean":
                        cap_parser.add_argument(f"--{prop_name}", action="store_true", help=help_text)
                    else:
                        cap_parser.add_argument(f"--{prop_name}", required=required, help=help_text)

    def execute(self, args: Optional[List[str]] = None, context: dict = None):
        if context is None:
            context = {}

        parsed_args = self.parser.parse_args(args)

        if not parsed_args.capability:
            self.parser.print_help()
            return

        cap = self.registry.get(parsed_args.capability)

        # Convert args namespace to dict, removing the 'capability' key
        kwargs = vars(parsed_args).copy()
        del kwargs['capability']

        context["surface"] = "cli"

        try:
            result = cap.execute(kwargs, context)

            output = {"result": result}
            if cap.evidence_required:
                output["effect_receipt"] = {
                    "capability_id": cap.capability_id,
                    "version": cap.version,
                    "domain_owner": cap.domain_owner,
                    "surface": "cli",
                    "effect_class": cap.effect_class,
                    "evidence": "generated by CLI adapter"
                }
            print(json.dumps(output, indent=2))
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
