from typing import Any, Dict
from .registry import CapabilityRegistry
import uuid

class HarnessAdapter:
    """
    Adapter bridging the AI-Native Capability Fabric with the Tech OS Harness Runtime.
    """
    def __init__(self, registry: CapabilityRegistry, harness_name: str = "default_harness"):
        self.registry = registry
        self.harness_name = harness_name

    def execute_capability(self, capability_id: str, arguments: dict, context: dict = None) -> Any:
        if context is None:
            context = {}

        cap = self.registry.get(capability_id)
        if not cap or "harness" not in cap.supported_surfaces:
            raise ValueError(f"Capability {capability_id} not found or not supported via harness")

        context["surface"] = "harness"
        context["harness_name"] = self.harness_name
        context["execution_id"] = f"hexec-{uuid.uuid4().hex[:8]}"

        result = cap.execute(arguments, context)

        if cap.evidence_required:
            result = self._wrap_with_receipt(cap, arguments, result, context)

        return result

    def _wrap_with_receipt(self, cap, args, result, context):
        return {
            "effect_receipt": {
                "capability_id": cap.capability_id,
                "version": cap.version,
                "domain_owner": cap.domain_owner,
                "surface": "harness",
                "harness_name": self.harness_name,
                "execution_id": context["execution_id"],
                "effect_class": cap.effect_class,
                "evidence": "generated by Harness adapter"
            },
            "data": result
        }
