from typing import Any, Dict
from .registry import CapabilityRegistry

class MCPAdapter:
    def __init__(self, registry: CapabilityRegistry):
        self.registry = registry

    def list_tools(self) -> list:
        tools = []
        for cap in self.registry.list_capabilities():
            if "mcp" in cap.supported_surfaces:
                tools.append({
                    "name": cap.capability_id,
                    "description": cap.intent,
                    "inputSchema": cap.input_schema
                })
        return tools

    def call_tool(self, tool_name: str, arguments: dict, context: dict = None) -> Any:
        if context is None:
            context = {}

        cap = self.registry.get(tool_name)
        if not cap or "mcp" not in cap.supported_surfaces:
            raise ValueError(f"Tool {tool_name} not found or not supported via MCP")

        context["surface"] = "mcp"
        result = cap.execute(arguments, context)

        if cap.evidence_required:
            result = self._wrap_with_receipt(cap, arguments, result)

        return result

    def _wrap_with_receipt(self, cap, args, result):
        return {
            "effect_receipt": {
                "capability_id": cap.capability_id,
                "version": cap.version,
                "domain_owner": cap.domain_owner,
                "surface": "mcp",
                "effect_class": cap.effect_class,
                "evidence": "generated by MCP adapter"
            },
            "data": result
        }
