import importlib.util,json,os,sqlite3,sys,tempfile,time,unittest
from pathlib import Path
P=Path(__file__).with_name("harness_runtime.py"); s=importlib.util.spec_from_file_location("hr",P); hr=importlib.util.module_from_spec(s); s.loader.exec_module(hr); FIX=Path(__file__).with_name("fixture_process_tree.py")
def mkdb(p):
    c=sqlite3.connect(p); c.executescript("create table work(id integer primary key,title text); create table event(id integer primary key,work_id integer,harness text,kind text,payload text,at text default (datetime('now')));"); c.execute("insert into work(id,title) values(197,'Harness Runtime')"); c.commit(); c.close()
class T(unittest.TestCase):
    def setUp(self):
        self.t=tempfile.TemporaryDirectory(); self.b=Path(self.t.name); self.o=self.b/"owned"; self.o.mkdir(); self.lock=self.b/"lock.txt"; self.lock.write_text("v1\n"); self.wg=self.b/"uc.db"; mkdb(self.wg); self.store=hr.RuntimeStore(self.b/"runtime.db"); self.sink=hr.WorkGraphEventSink(self.wg); self.a=hr.LocalCLIAdapter(self.store,self.o,event_sink=self.sink)
    def tearDown(self): self.t.cleanup()
    def req(self,corr="corr-1",cmd=None,arts=None):
        return {"schema":"aspace.harness-execution-request.v1","request_id":"req-1","dispatch_id":"dispatch-1","work_id":197,"correlation_id":corr,"capability_id":hr.CAPABILITY_ID,"required_harness_capabilities":["process-tree","receipt"],"inputs":[],"desired_artifacts":arts or [],"authority_scopes":["runtime:inspect","runtime:prepare","harness:execute"],"timeout_seconds":30,"replay_policy":"resume-if-supported","return_route":{"origin_intent":"test","mission_id":"github-194","work_id":197,"cell_id":"p1p4","correlation_id":corr,"origin_capability":"ryan-build","terminal_consumer":"river-flow","evidence_sink":"workgraph:event","on_success":"river-flow","on_retry":"river-flow","on_unknown":"donna-recover","on_build_defect":"ryan-build","on_design_gap":"clara-design-forge"},"workspace":"ASpace_OS_V3","worktree":"Ryan","cwd":str(self.b),"runtime":"python","runtime_root":str(self.o/"prepared"/"fixture"),"dependency_refs":[str(self.lock)],"credential_profile_ref":"profile:test","quota_profile":"bounded","harness":"fixture-cli","harness_version":"1","adapter":"local-cli","provider":"local","model":None,"policy_decision_ref":"policy:allow","command":cmd or [sys.executable,str(FIX),"--parent-lifetime",".3","--child-lifetime",".3"]}
    def test_p1_fingerprint_determinism_and_drift(self):
        r=self.req(); a=self.a.inspect(r); b=self.a.inspect(r); self.assertEqual(a["fingerprint"],b["fingerprint"]); self.assertEqual(a["capability_version"],hr.CAPABILITY_VERSION); self.assertEqual(a["policy_version"],hr.POLICY_VERSION); self.lock.write_text("v2\n"); c=self.a.inspect(r); self.assertNotEqual(a["fingerprint"],c["fingerprint"]); self.assertNotEqual(a["dependency_hash"],c["dependency_hash"])
    def test_p2_prepare_idempotent_compensable_and_failed_receipt(self):
        before=os.environ.get("PATH"); r=self.req(); r.update({"prepare_id":"prep-ok","runtime_root":str(self.o/"prepared"/"ok")}); x=self.a.prepare(r); y=self.a.prepare(r); self.assertEqual(x["state"],"SUCCEEDED"); self.assertTrue(y["replayed"]); self.assertEqual(before,os.environ.get("PATH")); root=Path(x["cleanup"]["runtime_root"]); self.assertTrue(root.exists()); self.assertEqual(self.a.preparer.cleanup(x)["state"],"COMPENSATED"); self.assertFalse(root.exists())
        f=self.req(); f.update({"prepare_id":"prep-fail","runtime_root":str(self.o/"prepared"/"fail"),"prepare_command":[sys.executable,"-c","raise SystemExit(7)"]}); z=self.a.prepare(f); self.assertEqual(z["state"],"FAILED"); self.assertEqual(self.store.get_prepare("prep-fail")["state"],"FAILED")
    def test_p3_whole_tree_cancel_no_owned_orphan(self):
        r=self.req("corr-cancel",[sys.executable,str(FIX),"--parent-lifetime","20","--child-lifetime","20"]); l=self.a.launch(r); time.sleep(1); o=self.a.observe(l["execution_id"]); self.assertEqual(o["lifecycle_state"],"RUNNING"); self.assertGreaterEqual(len(o["children"]),1); c=self.a.cancel(l["execution_id"]); self.assertEqual(c["lifecycle_state"],"CANCELLED"); snap=hr.process_snapshot(); row=self.store.get_execution(l["execution_id"]); self.assertFalse(any(int(p) in snap for p in row["known_pids"]))
    def test_p3_parent_interruption_unknown_never_blind_retry(self):
        r=self.req("corr-unknown",[sys.executable,str(FIX),"--parent-lifetime","20","--child-lifetime","20"]); l=self.a.launch(r); time.sleep(1); self.assertGreaterEqual(len(self.a.observe(l["execution_id"])["children"]),1); o=self.a.interrupt_root_only(l["execution_id"]); self.assertEqual(o["lifecycle_state"],"UNKNOWN"); rec=self.a.reconcile(l["execution_id"]); self.assertEqual(rec["effect_state"],"UNKNOWN"); self.assertFalse(rec["retry_safe"]); self.assertIn("Donna",rec["recovery_hint"]); self.a.cancel(l["execution_id"])
    def test_p3_success_collect_receipt_yes(self):
        art=self.b/"report"/"verdict.json"; code=f"from pathlib import Path; p=Path(r'{art}'); p.parent.mkdir(parents=True,exist_ok=True); p.write_text('{{\"verdict\":\"PASS\"}}')"; r=self.req("corr-success",[sys.executable,"-c",code],[str(art)]); l=self.a.launch(r); o=self.a.wait(l["execution_id"],timeout_seconds=5); self.assertEqual(o["lifecycle_state"],"SUCCEEDED"); self.assertEqual(self.a.collect(l["execution_id"])["artifact_refs"],[str(art.resolve())]); self.assertEqual(self.a.reconcile(l["execution_id"])["effect_state"],"YES")
    def test_p4_release_and_event_chain(self):
        corr="corr-events"; rel=hr.capability_release(contract_ref="contracts/HARNESS_RUNTIME_CONTRACTS.schema.json",artifact_refs=["runtime/harness_runtime.py"],acceptance_evidence=["P1","P2","P3","P4"],adapter_refs=["adapter:local-cli"],rollback_ref="rollback:p1p4"); rel["correlation_id"]=corr; self.sink.emit(197,"capability_release",rel); p=self.req(corr); p.update({"prepare_id":"prep-events","runtime_root":str(self.o/"prepared"/"events")}); self.a.prepare(p); r=self.req(corr,[sys.executable,"-c","print('ok')"]); l=self.a.launch(r); self.a.wait(l["execution_id"],timeout_seconds=5); self.a.reconcile(l["execution_id"]); kinds=[x["kind"] for x in self.sink.read_chain(197,corr)]
        for k in ("capability_release","runtime_prepared","harness_execution_started","harness_observed","harness_execution_receipt"): self.assertIn(k,kinds)
    def test_no_chatgpt_session_state_required(self):
        r=self.req("corr-sessionless",[sys.executable,"-c","print('sessionless')"]); self.assertNotIn("chatgpt",json.dumps(r).lower()); l=self.a.launch(r); self.a.wait(l["execution_id"],timeout_seconds=5); self.assertIn(self.a.reconcile(l["execution_id"])["effect_state"],{"YES","NO","UNKNOWN"})
if __name__=="__main__":unittest.main(verbosity=2)
