-- A'Space IPBD Intent SSOT
-- RECORD OF LIVE DEPLOYMENT: already applied to Aspace OS / Agent OS Backend.
-- Do not reapply blindly; reconcile against the live schema first.
-- Deployed to Supabase project: Aspace OS / Agent OS Backend
-- Principle: capture is append-first; intentions persist until explicit resolution/closure.

create schema if not exists aspace;

create table if not exists aspace.capture_event (
  id uuid primary key default gen_random_uuid(),
  source_type text not null,
  source_ref text,
  source_event_id text,
  dedupe_key text not null unique,
  actor text,
  raw_text text,
  raw_payload jsonb not null default '{}'::jsonb,
  capture_status text not null default 'captured'
    check (capture_status in ('captured','parsed','linked','ignored','error')),
  captured_at timestamptz not null default now(),
  processed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists aspace.intent (
  id uuid primary key default gen_random_uuid(),
  kind text not null
    check (kind in ('INTENTION','BESOIN','PROBLEMATIQUE','DESIR','MIXED','UNCLASSIFIED')),
  verbatim text not null,
  normalized_summary text,
  status text not null default 'INBOX'
    check (status in ('INBOX','CLARIFIED','ORGANIZED','ACTIVE','WAITING','SOMEDAY','RESOLVED','CLOSED','CANCELED')),
  core text check (core in ('A0','KERNEL','LIFE','BUZZ')),
  owner_role text,
  life_domain text,
  framework_map jsonb not null default '{}'::jsonb,
  priority integer not null default 0,
  horizon text,
  parent_intent_id uuid references aspace.intent(id) on delete set null,
  canonical_capture_id uuid references aspace.capture_event(id) on delete restrict,
  closure_reason text,
  closure_evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz
);

create table if not exists aspace.intent_source (
  intent_id uuid not null references aspace.intent(id) on delete cascade,
  capture_event_id uuid not null references aspace.capture_event(id) on delete restrict,
  relation text not null default 'supports'
    check (relation in ('origin','supports','updates','contradicts','duplicates')),
  created_at timestamptz not null default now(),
  primary key (intent_id, capture_event_id)
);

create table if not exists aspace.intent_link (
  id bigint generated by default as identity primary key,
  intent_id uuid not null references aspace.intent(id) on delete cascade,
  target_type text not null,
  target_ref text not null,
  relation text not null default 'projects_to',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(intent_id, target_type, target_ref, relation)
);

create table if not exists aspace.intent_transition (
  id bigint generated by default as identity primary key,
  intent_id uuid not null references aspace.intent(id) on delete cascade,
  from_status text,
  to_status text not null,
  reason text,
  actor text,
  evidence jsonb not null default '{}'::jsonb,
  at timestamptz not null default now()
);

create table if not exists aspace.capture_cursor (
  source_type text not null,
  source_scope text not null,
  cursor_value text,
  watermark_at timestamptz,
  last_capture_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (source_type, source_scope)
);

create index if not exists capture_event_source
  on aspace.capture_event(source_type, captured_at desc);
create index if not exists intent_status_priority
  on aspace.intent(status, priority desc, created_at);
create index if not exists intent_core_owner
  on aspace.intent(core, owner_role, status);
create index if not exists intent_link_target
  on aspace.intent_link(target_type, target_ref);
create index if not exists intent_transition_intent
  on aspace.intent_transition(intent_id, id);

create or replace function aspace.touch_intent_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();

  if new.status in ('RESOLVED','CLOSED','CANCELED')
     and coalesce(nullif(trim(new.closure_reason),''),'') = ''
  then
    raise exception 'intent_terminal_state_requires_closure_reason';
  end if;

  if new.status = 'RESOLVED' and old.status <> 'RESOLVED' then
    new.resolved_at = coalesce(new.resolved_at, now());
  end if;

  if new.status in ('CLOSED','CANCELED')
     and old.status not in ('CLOSED','CANCELED')
  then
    new.closed_at = coalesce(new.closed_at, now());
  end if;

  return new;
end;
$$;

drop trigger if exists touch_intent on aspace.intent;
create trigger touch_intent
before update on aspace.intent
for each row execute function aspace.touch_intent_updated_at();

create or replace function aspace.log_intent_transition()
returns trigger language plpgsql as $$
begin
  if old.status is distinct from new.status then
    insert into aspace.intent_transition(intent_id, from_status, to_status, reason, actor, evidence)
    values (
      new.id, old.status, new.status, new.closure_reason,
      coalesce(new.owner_role, 'system'), new.closure_evidence
    );
  end if;
  return new;
end;
$$;

drop trigger if exists log_intent_transition on aspace.intent;
create trigger log_intent_transition
after update of status on aspace.intent
for each row execute function aspace.log_intent_transition();

create or replace function aspace.forbid_intent_delete()
returns trigger language plpgsql as $$
begin
  raise exception 'intent_rows_are_persistent_close_them_do_not_delete_them';
end;
$$;

drop trigger if exists forbid_intent_delete on aspace.intent;
create trigger forbid_intent_delete
before delete on aspace.intent
for each row execute function aspace.forbid_intent_delete();

create or replace function aspace.capture_ipbd(
  p_kind text,
  p_verbatim text,
  p_source_type text,
  p_dedupe_key text,
  p_source_ref text default null,
  p_source_event_id text default null,
  p_actor text default null,
  p_raw_payload jsonb default '{}'::jsonb,
  p_core text default null,
  p_owner_role text default null,
  p_framework_map jsonb default '{}'::jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = aspace, public
as $$
declare
  v_capture_id uuid;
  v_intent_id uuid;
begin
  if p_kind not in ('INTENTION','BESOIN','PROBLEMATIQUE','DESIR','MIXED','UNCLASSIFIED') then
    raise exception 'invalid_ipbd_kind';
  end if;

  insert into aspace.capture_event(
    source_type, source_ref, source_event_id, dedupe_key,
    actor, raw_text, raw_payload, metadata
  )
  values (
    p_source_type, p_source_ref, p_source_event_id, p_dedupe_key,
    p_actor, p_verbatim, p_raw_payload, p_metadata
  )
  on conflict (dedupe_key) do update
    set metadata = aspace.capture_event.metadata || excluded.metadata
  returning id into v_capture_id;

  select i.id into v_intent_id
  from aspace.intent i
  join aspace.intent_source s on s.intent_id = i.id
  where s.capture_event_id = v_capture_id
  order by i.created_at
  limit 1;

  if v_intent_id is null then
    insert into aspace.intent(
      kind, verbatim, core, owner_role, framework_map, canonical_capture_id
    )
    values (
      p_kind, p_verbatim, p_core, p_owner_role, p_framework_map, v_capture_id
    )
    returning id into v_intent_id;

    insert into aspace.intent_source(intent_id, capture_event_id, relation)
    values (v_intent_id, v_capture_id, 'origin');

    insert into aspace.intent_transition(intent_id, from_status, to_status, reason, actor)
    values (v_intent_id, null, 'INBOX', 'captured', coalesce(p_actor,'system'));
  end if;

  update aspace.capture_event
     set capture_status='linked', processed_at=coalesce(processed_at, now())
   where id=v_capture_id;

  return v_intent_id;
end;
$$;

create or replace view aspace.v_intent_inbox as
select i.*, ce.source_type, ce.source_ref, ce.captured_at
from aspace.intent i
left join aspace.capture_event ce on ce.id=i.canonical_capture_id
where i.status='INBOX'
order by i.priority desc, i.created_at;

create or replace view aspace.v_intent_open as
select i.*
from aspace.intent i
where i.status not in ('RESOLVED','CLOSED','CANCELED')
order by i.priority desc, i.updated_at desc;

create or replace view aspace.v_intent_unresolved_age as
select i.*, now() - i.created_at as age, now() - i.updated_at as since_update
from aspace.intent i
where i.status not in ('RESOLVED','CLOSED','CANCELED')
order by i.created_at;

alter table aspace.capture_event enable row level security;
alter table aspace.intent enable row level security;
alter table aspace.intent_source enable row level security;
alter table aspace.intent_link enable row level security;
alter table aspace.intent_transition enable row level security;
alter table aspace.capture_cursor enable row level security;

revoke all on aspace.capture_event, aspace.intent, aspace.intent_source,
  aspace.intent_link, aspace.intent_transition, aspace.capture_cursor
  from anon, authenticated;

grant select, insert, update on aspace.capture_event to service_role;
grant select, insert, update on aspace.intent to service_role;
grant select, insert on aspace.intent_source to service_role;
grant select, insert, update, delete on aspace.intent_link to service_role;
grant select, insert on aspace.intent_transition to service_role;
grant select, insert, update on aspace.capture_cursor to service_role;
grant usage, select on all sequences in schema aspace to service_role;
grant execute on function aspace.capture_ipbd(
  text,text,text,text,text,text,text,jsonb,text,text,jsonb,jsonb
) to service_role;
