-- Synced from Supabase project Agent OS Backend (20260927121424)
-- Migration: aspace_machine_blackboard_v1
-- This file records the already-applied live migration; do not reapply blindly.

create schema if not exists aspace;

revoke all on schema aspace from public, anon, authenticated;
grant usage on schema aspace to service_role;

create table if not exists aspace.tape (
  id bigint generated by default as identity primary key,
  path text not null unique,
  sha256 text not null,
  source_uri text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists aspace.work (
  id bigint generated by default as identity primary key,
  tape_id bigint references aspace.tape(id),
  layer text not null check (layer in ('A0','L0','L1','L2')),
  core text check (core in ('A0','KERNEL','LIFE','BUZZ')),
  title text not null,
  status text not null default 'pending'
    check (status in ('pending','claimed','review','done','failed','blocked','waiting')),
  wake_at timestamptz,
  priority integer not null default 0,
  parent_id bigint references aspace.work(id),
  attempts integer not null default 0,
  external_refs jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists work_ready
  on aspace.work(status, layer, priority desc, id);
create index if not exists work_core_status
  on aspace.work(core, status, priority desc, id);

create table if not exists aspace.work_dependency (
  work_id bigint not null references aspace.work(id) on delete cascade,
  depends_on_id bigint not null references aspace.work(id) on delete cascade,
  kind text not null default 'blocks',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (work_id, depends_on_id, kind),
  check (work_id <> depends_on_id)
);

create table if not exists aspace.claim (
  work_id bigint primary key references aspace.work(id) on delete cascade,
  harness text not null,
  claimed_at timestamptz not null default now(),
  expires_at timestamptz not null,
  lease_token uuid not null default gen_random_uuid(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists aspace.session_binding (
  id uuid primary key default gen_random_uuid(),
  work_id bigint references aspace.work(id) on delete cascade,
  provider text not null,
  session_id text not null,
  role_name text,
  manager_role text,
  status text not null default 'active'
    check (status in ('active','waiting','completed','failed','closed','unknown')),
  repo text,
  branch text,
  head_sha text,
  pr_number integer,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz,
  unique(provider, session_id)
);
create index if not exists session_binding_work
  on aspace.session_binding(work_id, status);

create table if not exists aspace.prediction (
  id bigint generated by default as identity primary key,
  work_id bigint not null references aspace.work(id) on delete cascade,
  claim_text text not null,
  confidence double precision not null check (confidence > 0.0 and confidence < 1.0),
  predicted_at timestamptz not null default now(),
  outcome integer check (outcome in (0,1)),
  scored_at timestamptz
);
create index if not exists prediction_work on aspace.prediction(work_id, id);

create table if not exists aspace.evidence (
  id bigint generated by default as identity primary key,
  work_id bigint references aspace.work(id) on delete cascade,
  session_binding_id uuid references aspace.session_binding(id) on delete set null,
  kind text not null,
  uri text,
  sha256 text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists evidence_work on aspace.evidence(work_id, id);

create table if not exists aspace.event (
  id bigint generated by default as identity primary key,
  work_id bigint references aspace.work(id) on delete cascade,
  session_binding_id uuid references aspace.session_binding(id) on delete set null,
  harness text,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  at timestamptz not null default now()
);
create index if not exists event_work on aspace.event(work_id, id);
create index if not exists event_time on aspace.event(at desc);

create table if not exists aspace.dlq (
  id bigint generated by default as identity primary key,
  work_id bigint references aspace.work(id) on delete set null,
  session_binding_id uuid references aspace.session_binding(id) on delete set null,
  owner text not null,
  source_surface text not null,
  failure_class text not null,
  attempt integer not null default 1,
  retry_budget integer not null default 2,
  last_evidence_id bigint references aspace.evidence(id) on delete set null,
  retry_after timestamptz,
  wake_condition text,
  next_owner text,
  escalation_target text,
  status text not null default 'DLQ_PENDING'
    check (status in ('DLQ_PENDING','RECOVERED','ESCALATED')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists dlq_status on aspace.dlq(status, retry_after, id);

create table if not exists aspace.workspace_world (
  world_id text primary key,
  category text not null,
  repo text,
  local_path text,
  codespace_path text,
  authority text,
  status text not null default 'registered',
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function aspace.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_work on aspace.work;
create trigger touch_work
before update on aspace.work
for each row execute function aspace.touch_updated_at();

drop trigger if exists touch_session_binding on aspace.session_binding;
create trigger touch_session_binding
before update on aspace.session_binding
for each row execute function aspace.touch_updated_at();

drop trigger if exists touch_dlq on aspace.dlq;
create trigger touch_dlq
before update on aspace.dlq
for each row execute function aspace.touch_updated_at();

create or replace function aspace.enforce_work_transition()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('review','done')
     and not exists (
       select 1 from aspace.prediction p where p.work_id = new.id
     )
  then
    raise exception 'loi_prediction: aucune prediction enregistree avant execution';
  end if;

  if new.status = 'done' and old.status <> 'review' then
    raise exception 'loi_detachement: done exige un passage par review';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_work_transition on aspace.work;
create trigger enforce_work_transition
before update of status on aspace.work
for each row execute function aspace.enforce_work_transition();

create or replace view aspace.v_ready as
select w.*
from aspace.work w
where w.status = 'pending'
order by w.priority desc, w.id;

create or replace view aspace.v_calibration as
select round(confidence::numeric, 1) as bucket,
       count(*) as n,
       avg(outcome) as taux_reel
from aspace.prediction
where outcome is not null
group by round(confidence::numeric, 1)
order by bucket;

create or replace view aspace.v_active_sessions as
select sb.*, w.title as work_title, w.core, w.status as work_status
from aspace.session_binding sb
left join aspace.work w on w.id = sb.work_id
where sb.status in ('active','waiting');

grant select, insert, update, delete on all tables in schema aspace to service_role;
grant usage, select on all sequences in schema aspace to service_role;
grant select on all tables in schema aspace to service_role;

insert into aspace.workspace_world
  (world_id, category, repo, local_path, codespace_path, authority, status, metadata)
values
  ('aspace_v3','core','Amdkn/Aspace_OS_V3','C:/Users/amado/ASpace_OS_V3','core/Aspace_OS_V3','canonical','active','{"manager":"Rick''s Verse"}'),
  ('agent_os','satellite','Amdkn/Agent-OS','C:/Users/amado/ASpace_OS_V3/00_Amadeus/10_Observers/agent-os','satellites/Agent-OS','satellite','registered','{}'),
  ('life_os_2026','satellite','Amdkn/Life-OS-2026',null,'satellites/Life-OS-2026','life_projection','registered','{"manager":"Doctor11"}'),
  ('business_os','business','Amdkn/BusinessOS',null,'business/BusinessOS','business_federation','registered','{"manager":"Doctor12"}'),
  ('business_office_3_os','business','Amdkn/Business-Office-3-OS',null,'business/Business-Office-3-OS','business_projection','registered','{"manager":"Doctor12"}')
on conflict (world_id) do update
set category = excluded.category,
    repo = excluded.repo,
    local_path = excluded.local_path,
    codespace_path = excluded.codespace_path,
    authority = excluded.authority,
    status = excluded.status,
    metadata = excluded.metadata,
    updated_at = now();
