-- Synced from Supabase project Agent OS Backend (20260927122738)
-- Migration: aspace_rls_and_world_catalog_v1
-- This file records the already-applied live migration; do not reapply blindly.

create table if not exists aspace.sync_run (
  id uuid primary key default gen_random_uuid(),
  world_id text not null references aspace.workspace_world(world_id) on delete cascade,
  source_git_sha text,
  source_branch text,
  source_root text,
  mode text not null default 'snapshot',
  status text not null default 'running'
    check (status in ('running','completed','failed')),
  asset_count integer not null default 0,
  entity_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists aspace.world_asset (
  id bigint generated by default as identity primary key,
  world_id text not null references aspace.workspace_world(world_id) on delete cascade,
  sync_run_id uuid references aspace.sync_run(id) on delete set null,
  relative_path text not null,
  asset_type text not null,
  media_type text,
  sha256 text not null,
  git_sha text,
  size_bytes bigint not null default 0,
  content_text text,
  content_json jsonb,
  metadata jsonb not null default '{}'::jsonb,
  observed_at timestamptz,
  synced_at timestamptz not null default now(),
  unique(world_id, relative_path)
);
create index if not exists world_asset_type on aspace.world_asset(world_id, asset_type);
create index if not exists world_asset_sha on aspace.world_asset(sha256);

create table if not exists aspace.world_entity (
  id bigint generated by default as identity primary key,
  world_id text not null references aspace.workspace_world(world_id) on delete cascade,
  sync_run_id uuid references aspace.sync_run(id) on delete set null,
  entity_type text not null,
  entity_key text not null,
  display_name text,
  source_path text not null,
  source_asset_id bigint references aspace.world_asset(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz,
  synced_at timestamptz not null default now(),
  unique(world_id, entity_type, entity_key)
);
create index if not exists world_entity_type on aspace.world_entity(world_id, entity_type);
create index if not exists world_entity_source on aspace.world_entity(source_path);

do $$
declare
  t text;
begin
  foreach t in array array[
    'tape','work','work_dependency','claim','session_binding','prediction',
    'evidence','event','dlq','workspace_world','sync_run','world_asset','world_entity'
  ]
  loop
    execute format('alter table aspace.%I enable row level security', t);
    execute format('alter table aspace.%I force row level security', t);
  end loop;
end $$;

revoke all on all tables in schema aspace from public, anon, authenticated;
revoke all on all sequences in schema aspace from public, anon, authenticated;
grant usage on schema aspace to service_role;
grant select, insert, update, delete on all tables in schema aspace to service_role;
grant usage, select on all sequences in schema aspace to service_role;

create or replace view aspace.v_world_catalog as
select
  w.world_id,
  w.category,
  w.repo,
  w.status as world_status,
  count(distinct a.id) as asset_count,
  count(distinct e.id) as entity_count,
  max(a.synced_at) as last_asset_sync,
  max(e.synced_at) as last_entity_sync
from aspace.workspace_world w
left join aspace.world_asset a on a.world_id = w.world_id
left join aspace.world_entity e on e.world_id = w.world_id
group by w.world_id, w.category, w.repo, w.status;

create or replace view aspace.v_agent_os_entities as
select entity_type, entity_key, display_name, source_path, payload, observed_at, synced_at
from aspace.world_entity
where world_id = 'agent_os';
